#!/bin/sh

mvn package

cp target/liars-dice-sample-java-1.0-jar-with-dependencies.jar ../liars-dice/dist/linux-x64/java
cp target/liars-dice-sample-java-1.0-jar-with-dependencies.jar ../liars-dice/dist/win-x64/java
